# NC 입니당!!!!
spring:
  application:
    name: nc

  profiles:
    active: nc

  cloud:
    config:
      server:
        svn:
          uri: http://172.21.251.13/svn/Tools
          username: jji
          password: mistil12!@
          default-label: trunk

        health:
          repositories:
            svn:
              label: trunk

server:
  port: 8888

management:
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - quartz
          - caches
